name: dino
description: Dino just a im

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.6.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mqtt_client: ^9.6.6
  faker: ^2.0.0 #假数据
  i18n_extension: ^4.2.1 # 多语言支持
  video_player: ^2.3.0
  flutter_markdown: ^0.6.9+1 #markdown 支持
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15
  http: ^0.13.4



dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_driver:
#    sdk: flutter
#  integration_test:
#    sdk: flutter
#  test: ^1.21.4
#  vm_service: ^7.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
